### ISSUE TITLE
SERVER_TYPE=TCP causes crash

### ISSUE THREAD

**Issue by SamKr** [dorel14/3CX-Cdr-Server#62]
**Describe the bug**
When `SERVER_TYPE` is configured as `TCP`, even when setting the `SERVER_PORT` variable, `3cxcdrserver-1` keeps crashing with the following error:

```
3cxcdrserver-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
3cxcdrserver-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
3cxcdrserver-1  | /home/appuser/app
3cxcdrserver-1  | Traceback (most recent call last):
3cxcdrserver-1  |   File "/home/appuser/app/srv/runserver.py", line 63, in <module>
3cxcdrserver-1  |     client_config = get_client_config(server_type)
3cxcdrserver-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3cxcdrserver-1  |   File "/home/appuser/app/myhelpers/config.py", line 52, in get_client_config
3cxcdrserver-1  |     'port': env_vars['SERVER_PORT']
3cxcdrserver-1  |             ~~~~~~~~^^^^^^^^^^^^^^^
3cxcdrserver-1  | KeyError: 'SERVER_PORT'
3cxcdrserver-1 exited with code 0
```

**Additional context**
I'm running through Docker on Debian 12. Been tweaking the configs all day (if I get this working, I'll create some PR's for you with extra troubleshooting / readme info if you want). I have everything working except this part. 

Something that may be relevant:

In `config.py`, I don't see the `SERVER_PORT` variable in the `env_vars` array:

https://github.com/dorel14/3CX-Cdr-Server/blob/master/myhelpers/config.py

![image](https://github.com/user-attachments/assets/cbbf7070-2c17-4298-a69b-9026afc70c8e)

Yet it tries to grab it from that array:

![image](https://github.com/user-attachments/assets/2e71fde7-11d9-4338-8c3b-1eb379b7d462)

Perhaps this is the issue?

Thanks for sharing this great project, and thanks in advance for your help!

**Comment by SamKr** [comment]
Update: I manually edited config.py to add the follow entry to the array (note that the 30000 is my arbitarily picked port):

`'SERVER_PORT': int(os.environ.get('SERVER_PORT', '30000')),`

And that solved the issue.

**Comment by dorel14** [comment]
Hello , happy to hear that you solved your issue.

The bug is exactly where you point it, feel free to submit a PR

Thx , next version will bring some more features

**Comment by SamKr** [comment]
I'll start working on some PRs in the coming days :) 

quick question, do you have any other grafana dashboards apart from the basic default one?

**Comment by SamKr** [comment]
Created the first PRs, let me know if something not up to your standards.

If you want, I can also work on your wiki, to add troubleshooting/info that I would've found useful. Easiest way is if you grant me editor access to them since they're not cloned with the rest.

**Comment by dorel14** [comment]
I sent you an invite to collaborate to repo and wiki

**Comment by SamKr** [comment]
Ah sorry, missed your second line, just merged them. It's in the dev branch so nothing's in main. 

I'll tinker with the wiki during the coming days, thanks for the invite 👋
