### ISSUE TITLE
DB won't create and use "postgres_user" value + 404 not found on web pages

### ISSUE THREAD

**Issue by Shunfry** [dorel14/3CX-Cdr-Server#77]
Hello 😄 

**Describe the bug**

1) Everything starting but I got this message on the log :

<pre><font color="#A2734C">db-1            | </font>2024-11-12 10:35:04.021 CET [76] FATAL:  database &quot;3cxdb&quot; does not exist
</pre>

2) can't access to localhost web server.
3) Need to manually add "WEB_SERVER_NAME" on the .env to correctly build.

**To Reproduce**

Bug appear after I download the last master build, reconfigure the .env and build the docker.

**Screenshots**

![image](https://github.com/user-attachments/assets/59cc6110-dc70-46ba-9ce3-e042fe6c7783)
![image](https://github.com/user-attachments/assets/e4a5265b-685f-4181-82dd-023ccf1755fc)
![image](https://github.com/user-attachments/assets/dff54d56-9f1a-4b24-89c9-0badc7e92be3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24
 - Last master branch from a github clone

________

Maybe all of this is because of the new "API" thing but I wanted to share my experience.

Best Regards.

**Comment by dorel14** [comment]
Hello 

The new WEB_SERVER_NAME replace the old NGINX_SERVER_NAME


You should use default login and password for the dB , i think with postgres / postgres database will bé created 

Normaly, you dont have to recreate dB on update 😕, if it was created on previous launch

**Comment by Shunfry** [comment]
Thank you for your reply. I tried and if I change credentials that I originaly use, I got even more error :

![image](https://github.com/user-attachments/assets/338371f7-2176-41cb-9beb-d75d603388d7)

But if I stick the one I create, I got only the "database doesn't exist" think.

Best Regards.

**Comment by Shunfry** [comment]
I'm using master branch, get with git clone.

[log master.txt](https://github.com/user-attachments/files/17733121/log.master.txt)

**Comment by dorel14** [comment]
In log file, i see 
`PostgreSQL Database directory appears to contain a database; Skipping initialization'

That's you database is not created 

What was the name of your dB before update ?

**Comment by Shunfry** [comment]
It's the same DB as before, same name.
I will try to see what it's wrong next week.

Thank you.

**Comment by dorel14** [comment]
Perhaps you can test to start only thé PostgreSql container and in shell a 

' docker exe  -it container_name psql -c '\l' '

If ok , it will show you a list of database running
